# podman build -t b-sep-fedora-python -f Containerfile .
# podman build -t quay.io/kenmoini/b-sep-fedora-python:latest -f Containerfile .
# podman push quay.io/kenmoini/b-sep-fedora-python:latest
# podman pull quay.io/kenmoini/b-sep-fedora-python:latest

FROM registry.fedoraproject.org/f35/python3

USER 0

ADD pki/* /etc/pki/ca-trust/source/anchors/
RUN ls -al /etc/pki/ca-trust/source/anchors/ && update-ca-trust

RUN dnf install --disablerepo='*' --nodocs -y https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-35.noarch.rpm \
 && dnf install --disablerepo='*' --nodocs -y https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-35.noarch.rpm \
 && dnf clean all \
 && rm -rf /var/cache/yum

RUN dnf update -y \
 && dnf clean all \
 && rm -rf /var/cache/yum

USER 1001

CMD /bin/bash
