# podman build -t b-sep-fedora-python-ffmepg -f Containerfile .
# podman build -t quay.io/kenmoini/b-sep-fedora-python-ffmepg:latest -f Containerfile .
# podman push quay.io/kenmoini/b-sep-fedora-python-ffmepg:latest
# podman pull quay.io/kenmoini/b-sep-fedora-python-ffmepg:latest

FROM quay.io/kenmoini/b-sep-fedora-python:latest

USER 0

RUN dnf install -y ffmpeg \
 && dnf clean all \
 && rm -rf /var/cache/yum

USER 1001

CMD /bin/bash
