# podman build -t gopro-control -f Containerfile .
# podman build -t quay.io/kenmoini/gopro-control:latest -f Containerfile .
# podman push quay.io/kenmoini/gopro-control:latest
# mkdir /tmp/gopro-videos
# podman run --name gopro-control -d --rm -v /tmp/gopro-videos:/opt/app-root/src/videos --net host gopro-control
# podman run --name gopro-control -d --rm -v /tmp/gopro-videos:/opt/app-root/src/videos --net host quay.io/kenmoini/gopro-control:latest
#FROM registry.access.redhat.com/ubi8/python-39@sha256:526b701cf4710a1c0562c0807b4815b38ac817bf14ed6c066f48fb66aac3a8b8
#FROM registry.fedoraproject.org/f35/python3

FROM quay.io/kenmoini/b-sep-fedora-python:latest

ENV FLASK_RUN_PORT 8181
ENV FLASK_RUN_HOST 0.0.0.0

USER 0

RUN dnf install -y https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-35.noarch.rpm \
 && dnf install -y https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-35.noarch.rpm \
 && dnf clean all \
 && rm -rf /var/cache/yum

RUN dnf install -y ffmpeg \
 && dnf clean all \
 && rm -rf /var/cache/yum

ADD app-src .

RUN pip install -r requirements.txt \
 && chown -R 1001:0 ./ \
 && chmod 777 ./videos \
 && chmod a+x /opt/app-root/src/start.sh

USER 1001

#CMD flask --app gopro-shoot-video run
CMD /opt/app-root/src/start.sh
