apiVersion: apps/v1
kind: Deployment
metadata:
  name: symphony
  namespace: symphony
  labels:
    app: symphony
spec:
  selector:
    matchLabels:
      app: symphony
  replicas: 1
  template:
    metadata:
      labels:
        app: symphony
    spec:
      containers:
        - name: symphony
          hostNetwork: true
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            seccompProfile:
              type: RuntimeDefault
            capabilities:
              drop:
                - ALL
          resources:
            limits:
              cpu: '1'
              memory: 1Gi
            requests:
              cpu: '500m'
              memory: 500Mi
          image: quay.io/kenmoini/symphony:latest
          env:
            - name: FLASK_RUN_PORT
              value: "9191"
            - name: FLASK_RUN_HOST
              value: "0.0.0.0"
          ports:
            - containerPort: 9191
              protocol: TCP
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  paused: false
