# Example values for running Label Studio on OpenShift

app:
  podSecurityContext:
    enabled: false
  containerSecurityContext:
    enabled: false
  rbac:
    create: true
  # see https://docs.openshift.com/container-platform/3.11/architecture/networking/routes.html#architecture-routes-support-for-ingress
  # cli ex: `oc expose svc labelstudio-ls-app` 
  ingress:
    enabled: false
    annotations:
      # note: the annotation below will allow a route to be created using a default wildcard certificate
      route.openshift.io/termination: edge
    # note: you will need to modify 'host' to your cluster domain
    #host: labelstudio.apps.sno.kemo.edge
    # note: below will also allow a route to be created using a default wildcard certificate
    # tls:
    #   - secretName: null
  pgConfig:
    host: "ls-postgresql"
    dbName: "postgres"
    userName: "postgres"
    password:
      secretName: "ls-postgres-configuration"
      secretKey: "password"

postgresql:
  enabled: false # bitnami postgresql does not support Arm architecture
  primary:
    podSecurityContext:
      enabled: false
    containerSecurityContext:
      enabled: false