apiVersion: apps/v1
kind: Deployment
metadata:
  name: sauron
  namespace: sauron
  labels:
    app: sauron
spec:
  template:
    spec:
      containers:
        - name: uruhara
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            seccompProfile:
              type: RuntimeDefault
            capabilities:
              drop:
                - ALL
          resources:
            limits:
              cpu: '8'
              memory: 16Gi
              nvidia.com/gpu: 1
            requests:
              cpu: '2'
              memory: 2Gi
              nvidia.com/gpu: 1
          image: quay.io/kenmoini/uruhara:4d3785369a0821ba397a7867b8f6a2eb3d9c782b
          ports:
            - containerPort: 8777
              protocol: TCP
          volumeMounts:
            - name: shared-data
              mountPath: "/shared-data"
              readOnly: false
            - name: model-data
              mountPath: "/opt/models"
              readOnly: false
