apiVersion: apps/v1
kind: Deployment
metadata:
  name: sauron
  namespace: sauron
  labels:
    app: sauron
spec:
  template:
    spec:
      containers:
        - name: uruhara
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            seccompProfile:
              type: RuntimeDefault
            capabilities:
              drop:
                - ALL
          resources:
            limits:
              cpu: '1'
              memory: 1Gi
              nvidia.com/gpu: 1
            requests:
              cpu: '500m'
              memory: 500Mi
              nvidia.com/gpu: 1
          image: quay.io/kenmoini/uruhara:a736ee75feac8d7b2552e62d0964707f296ce4dc
          ports:
            - containerPort: 8777
              protocol: TCP
          volumeMounts:
            - name: shared-data
              mountPath: "/shared-data"
              readOnly: false