apiVersion: apps/v1
kind: Deployment
metadata:
  name: sauron
spec:
  template:
    spec:
      containers:
        - name: uruhara
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            seccompProfile:
              type: RuntimeDefault
            capabilities:
              drop:
                - ALL
          resources:
            limits:
              cpu: '1'
              memory: 1Gi
              nvidia.com/gpu: 1
            requests:
              cpu: '500m'
              memory: 500Mi
              nvidia.com/gpu: 1
          image: quay.io/kenmoini/uruhara:10f4151239d32fb10f881f0dc44aa7206b44b11d
          ports:
            - containerPort: 8777
              protocol: TCP
          volumeMounts:
            - name: shared-data
              mountPath: "/shared-data"
              readOnly: false