---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Deploys the roboflow-robot microservice
# namespace: roboflow-robot

resources:
  - namespace.yml
  - pvc.yml
  - deployment.yml
  - service.yml
  - route.yml
