---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rf-data
  namespace: roboflow-robot
  labels:
    app: roboflow-robot
spec:
  resources:
    requests:
      storage: 5Gi
  #capacity:
  #  storage: 5Gi
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
