---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: rf-data
  namespace: roboflow-robot
  labels:
    app: roboflow-robot
spec:
  resources:
    requests:
      storage: 5Gi
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
