# Or generate the secret with

# kubectl create secret generic rf-credentials -n roboflow-robot --from-literal=apiKey=SOME_KEY --from-literal=projectID=PROJECT_ID --from-literal=modelVersion=2
---
apiVersion: v1
kind: Secret
metadata:
  name: rf-credentials
  namespace: roboflow-robot
stringData:
  apiKey: roboflowAPIKey
  projectID: projectIDHere
  modelVersion: "2"
