apiVersion: apps/v1
kind: Deployment
metadata:
  name: sauron
  namespace: sauron
  labels:
    app: sauron
spec:
  template:
    spec:
      initContainers:
        - name: models
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            seccompProfile:
              type: RuntimeDefault
            capabilities:
              drop:
                - ALL
          resources:
            limits:
              cpu: '500m'
              memory: 512Mi
            requests:
              cpu: '128m'
              memory: 128Mi
          image: quay.io/kenmoini/darkness:sep-models-latest
          command:
            - /bin/bash
            - -c
            - |
              #!/usr/bin/env bash

              cp -vr /opt/pkg_models/* /opt/models/
          volumeMounts:
            - name: model-data
              mountPath: "/opt/models"
              readOnly: false
