---
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: kafka-ui
  namespace: kafka-cluster
spec:
  to:
    kind: Service
    name: kafka-ui
    weight: 100
  port:
    targetPort: http
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Allow
  wildcardPolicy: None