apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaBridge
metadata:
  name: my-bridge
  namespace: kafka-cluster
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  replicas: 1
  bootstrapServers: my-cluster-kafka-bootstrap:9092
  enableMetrics: true
  http:
    port: 8080