
# podman build -t py-server -f Containerfile .
# podman build -t quay.io/kenmoini/py-server:latest -f Containerfile .
# podman push quay.io/kenmoini/py-server:latest

# podman pull quay.io/kenmoini/py-server:latest
# podman run --name py-server -d --rm -p 7999:7999 py-server
# podman run --name py-server -d --rm -p 7999:7999 quay.io/kenmoini/py-server:latest

FROM quay.io/kenmoini/b-sep-fedora-python:latest

ENV PY_HTTP_SERVER_PORT 7999
ENV PY_HTTP_SERVER_HOST 0.0.0.0
ENV PY_HTTP_SERVER_DIRECTORY ./www-root/

USER 0

ADD app-src .

RUN chown -R 1001:0 ./ \
 && chmod a+x /opt/app-root/src/start.sh

USER 1001

CMD /opt/app-root/src/start.sh
