---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - multiclusterhub.yml
  - managedclusterset.yml
  - local-cluster-managedcluster.yml

transformers:
  - modifications/local-cluster-patch.yml
