apiVersion: operator.open-cluster-management.io/v1
kind: MultiClusterHub
metadata:
  name: multiclusterhub
  namespace: open-cluster-management
spec:
  availabilityConfig: Basic
  enableClusterBackup: false
  disableUpdateClusterImageSets: false
  separateCertificateManagement: false
  #disableHubSelfManagement: true
  #imagePullSecret: cluster-pull-secret
  #customCAConfigmap: cluster-root-ca-bundle
  overrides:
    components:
      - enabled: true
        name: multiclusterhub-repo
      - enabled: true
        name: search
      - enabled: true
        name: console
      - enabled: true
        name: insights
      - enabled: true
        name: grc
      - enabled: true
        name: cluster-lifecycle
      - enabled: true
        name: volsync
      - enabled: true
        name: multicluster-engine
      - enabled: false
        name: cluster-proxy-addon
      - enabled: false
        name: cluster-backup