# podman build -t symphony -f Containerfile .
# podman build -t quay.io/kenmoini/symphony:latest -f Containerfile .
# podman push quay.io/kenmoini/symphony:latest

# podman pull quay.io/kenmoini/symphony:latest
# podman run --name symphony -d --rm -p 9191:9191 symphony
# podman run --name symphony -d --rm -p 9191:9191 quay.io/kenmoini/symphony:latest

#FROM registry.fedoraproject.org/f35/python3
FROM quay.io/kenmoini/b-sep-fedora-python:latest

ENV FLASK_RUN_PORT 9191
ENV FLASK_RUN_HOST 0.0.0.0

USER 0

ADD app-src .

RUN pip install -r requirements.txt \
 && chown -R 1001:0 ./ \
 && chmod a+x /opt/app-root/src/start.sh

USER 1001

#CMD flask --app server run
CMD /opt/app-root/src/start.sh
