apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: consolelinks-label-studio
  namespace: rhacm-policies
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous
spec:
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: cl-label-studio
        spec:
          remediationAction: enforce
          severity: high
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: console.openshift.io/v1
                kind: ConsoleLink
                metadata:
                  name: label-studio-console-link
                spec:
                  applicationMenu:
                    imageURL: https://http-py-server.apps.sno.kemo.edge/consolelink-images/label-studio.png
                    section: Data Science
                  href: 'https://{{ ( index ( lookup "route.openshift.io/v1"  "Route" "label-studio" "label-studio").status.ingress 0 ).host }}'
                  location: ApplicationMenu
                  text: Label Studio
          pruneObjectBehavior: DeleteIfCreated