# Deploys the s3-shipper microservice that will take files from the system and upload them to S3/Minio
# namespace: s3-shipper

resources:
- namespace.yml
- rbac.yml
- deployment.yml
- service.yml
- route.yml