apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-chat
spec:
  template:
    spec:
      volumes:
        - name: chats
          emptyDir: null
          persistentVolumeClaim:
            claimName: chats