apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-chat
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  template:
    spec:
      volumes:
        - name: chats
          emptyDir: null
          persistentVolumeClaim:
            claimName: chats