apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: grafana
  name: grafana
  namespace: monitoring
spec:
  template:
    spec:
      volumes:
        - name: chats
          emptyDir: null
          persistentVolumeClaim:
            claimName: chats
      containers:
        - name: simple-chat
          volumeMounts:
            - name: chats
              mountPath: /opt/app-root/src/data