---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: chats
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
