
# podman build -t s3-shipper -f Containerfile .
# podman build -t quay.io/kenmoini/s3-shipper:latest -f Containerfile .
# podman push quay.io/kenmoini/s3-shipper:latest
# mkdir /tmp/dc-videos
# copy some things here
# podman run --name s3-shipper -d --rm -v /tmp/dc-videos:/opt/app-root/src/videos:ro -v /var/run/secrets/s3:/var/run/secrets/s3:ro -p 8888:8888 s3-shipper
# podman run --name s3-shipper -d --rm -v /tmp/dc-videos:/opt/app-root/src/videos:ro -v /var/run/secrets/s3:/var/run/secrets/s3:ro -p 8888:8888 quay.io/kenmoini/s3-shipper:latest

#FROM registry.fedoraproject.org/f35/python3
FROM quay.io/kenmoini/b-sep-fedora-python:latest

ENV FLASK_RUN_PORT 8888
ENV FLASK_RUN_HOST 0.0.0.0

USER 0

ADD app-src .

RUN pip install -r requirements.txt \
 && chown -R 1001:0 ./

USER 1001

CMD ["flask", "--app", "upload-to-s3", "run"]
