apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: minio-dev
  name: minio
  labels:
    app: minio
spec:
  selector:
    matchLabels:
      app: minio
  replicas: 1
  template:
    metadata:
      labels:
        app: minio
    spec:
      volumes:
        - name: minio-storage
          persistentVolumeClaim:
            claimName: minio-storage
      containers:
        - name: minio
          resources:
            limits:
              cpu: '2'
              memory: 2Gi
            requests:
              cpu: '1'
              memory: 500Mi
          image: quay.io/minio/minio:latest
          volumeMounts:
            - name: minio-storage
              mountPath: /data
          ports:
            - containerPort: 9000
              protocol: TCP
            - containerPort: 9090
              protocol: TCP
          env: []
          command:
            - /bin/bash
            - -c
          args:
            - minio server /data --console-address :9090
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  paused: false
