# Deploys Minio S3 service in a development environment
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yml
  - pvc.yml
  - deployment.yml
  - services.yml
  - routes.yml
  - init-job.yml
