---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: minio-dev
  name: minio-storage
  labels:
    app: minio
spec:
  resources:
    requests:
      storage: 100Gi
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
