apiVersion: apps/v1
kind: Deployment
metadata:
  name: sauron
  namespace: sauron
  labels:
    app: sauron
spec:
  selector:
    matchLabels:
      app: sauron
  replicas: 1
  template:
    metadata:
      labels:
        app: sauron
    spec:
      volumes:
        - name: s3-credentials
          secret:
            secretName: s3-credentials
        - name: shared-data
          emptyDir: {}
      containers:
        - name: sauron
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            seccompProfile:
              type: RuntimeDefault
            capabilities:
              drop:
                - ALL
          resources:
            limits:
              cpu: '1'
              memory: 1Gi
            requests:
              cpu: '500m'
              memory: 500Mi
          image: quay.io/kenmoini/sauron:b5090a7cf43e12f7526bee37a4a6aa247102eab5
          env:
            - name: SAURON_HTTP_SERVER_PORT
              value: "6669"
            - name: SAURON_HTTP_SERVER_HOST
              value: "0.0.0.0"

            - name: KAFKA_ENDPOINT
              value: "my-cluster-kafka-bootstrap.kafka-cluster.svc.cluster.local:9092"
            - name: KAFKA_TOPIC
              value: gopro-videos

            - name: S3_SECRET_PATH
              value: "/var/run/s3-credentials/"
            - name: S3_VERIFY_SSL
              value: "False" # True | False
            - name: S3_ENDPOINT_LINK
              value: minio-s3-minio-dev.apps.sno.kemo.edge
          ports:
            - containerPort: 6669
              protocol: TCP
          volumeMounts:
            - name: s3-credentials
              mountPath: "/var/run/s3-credentials"
              readOnly: true
            - name: shared-data
              mountPath: "/shared-data"
              readOnly: false

        - name: uruhara
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            seccompProfile:
              type: RuntimeDefault
            capabilities:
              drop:
                - ALL
          resources:
            limits:
              cpu: '1'
              memory: 1Gi
              nvidia.com/gpu: 1
            requests:
              cpu: '500m'
              memory: 500Mi
              nvidia.com/gpu: 1
          image: quay.io/kenmoini/uruhara:latest
          ports:
            - containerPort: 8777
              protocol: TCP
          volumeMounts:
            - name: shared-data
              mountPath: "/shared-data"
              readOnly: false
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%

