apiVersion: apps/v1
kind: Deployment
metadata:
  name: sauron
  namespace: sauron
  labels:
    app: sauron
spec:
  selector:
    matchLabels:
      app: sauron
  replicas: 1
  template:
    metadata:
      labels:
        app: sauron
    spec:
      containers:
        - name: sauron
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            seccompProfile:
              type: RuntimeDefault
            capabilities:
              drop:
                - ALL
          resources:
            limits:
              cpu: '1'
              memory: 1Gi
            requests:
              cpu: '500m'
              memory: 500Mi
          image: quay.io/kenmoini/sauron:ef3cb50541da2eb60a1948c2b4bd83d7942c3274
          env:
            - name: SAURON_HTTP_SERVER_PORT
              value: "6669"
            - name: SAURON_HTTP_SERVER_HOST
              value: "0.0.0.0"
            - name: KAFKA_ENDPOINT
              value: "my-cluster-kafka-bootstrap.kafka-cluster.svc.cluster.local:9092"
            - name: KAFKA_TOPIC
              value: gopro-videos
          ports:
            - containerPort: 6669
              protocol: TCP
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%

