# Or generate the secret with
# kubectl create secret generic s3-credentials -n s3-shipper --from-literal=access_key_id=SOME_KEY_ID --from-literal=access_key_secret=SOME_KEY_SECRET
# kubectl create secret generic minio-credentials -n s3-shipper --from-literal=access_key_id=SOME_KEY_ID --from-literal=access_key_secret=SOME_KEY_SECRET
---
apiVersion: v1
kind: Secret
metadata:
  name: s3-credentials
  namespace: sauron
stringData:
  access_key_id: uploadKey
  access_key_secret: uploadSecret

