---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: simple-chat-cm-job
  annotations:
    argocd.argoproj.io/sync-wave: "2"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: simple-chat-cm-job
  annotations:
    argocd.argoproj.io/sync-wave: "2"
rules:
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - get
      - list
      - exec
  - apiGroups:
      - ""
    resources:
      - pods/exec
    verbs:
      - create
  - apiGroups:
      - "operator.openshift.io"
    resources:
      - ingresscontrollers
    verbs:
      - get
      - list
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - create
      - delete
      - get
      - list
      - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: simple-chat-cm-job
  annotations:
    argocd.argoproj.io/sync-wave: "2"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: simple-chat-cm-job
subjects:
  - kind: ServiceAccount
    name: simple-chat-cm-job
    namespace: simple-chat
