---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-gpu-validation
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "9"
    argocd.argoproj.io/compare-options: IgnoreExtraneous
spec:
  syncPolicy:
    syncOptions:
      - RespectIgnoreDifferences=true
    automated:
      prune: true
      allowEmpty: true
      #selfHeal: false # overrides changes made on the cluster that drift from git state
  destination:
    name: local-cluster
  source:
    repoURL: 'https://github.com/kenmoini/smart-drone-patterns'
    targetRevision: HEAD
    path: openshift/apps/gpu-validation/
    #directory:
    #  recurse: true
    kustomize:
      version: v4.4.1
  project: edge-cluster