apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kafka-ui
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "5"
    argocd.argoproj.io/compare-options: IgnoreExtraneous
spec:
  destination:
    namespace: 'kafka-cluster'
    name: local-cluster
  project: edge-cluster
  sources:
    - chart: kafka-ui
      helm:
        valueFiles:
          - $values/openshift/helm/kafka-ui/strimzi-values.yml
      repoURL: 'https://provectus.github.io/kafka-ui-charts'
      targetRevision: 0.7.5
    - ref: values
      repoURL: 'https://github.com/kenmoini/smart-drone-patterns'
      targetRevision: main
    # Since the helm chart doesn't support the following, we'll use kustomize to patch the deployment
    - repoURL: 'https://github.com/kenmoini/smart-drone-patterns'
      targetRevision: HEAD
      path: openshift/helm/kafka-ui/patches/
      #directory:
      #  recurse: true
      kustomize:
        version: v4.4.1
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true