---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: operand-acm-lite
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  destination:
    server: 'https://kubernetes.default.svc'
  source:
    repoURL: 'https://github.com/kenmoini/smart-drone-patterns'
    targetRevision: HEAD
    path: openshift/services/acm-lite/instance/
    #directory:
    #  recurse: true
    kustomize:
      version: v4.4.1
  project: edge-cluster
  syncPolicy:
    automated:
      prune: true
      allowEmpty: true
      #selfHeal: false # overrides changes made on the cluster that drift from git state