name: Build App Container - Symphony Frontend
on:
  push:
    branches:
      - main
    paths:
      - apps/symphony/**
      - microshift/symphony/**
      - .github/workflows/build-app-symphony.yml

  # Schedule workflow run at 00:00 on Sunday
  schedule:
    - cron: '0 0 * * 0'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # Build the container
  build-container:
    name: Build Container
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:

    - name: Check out code
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GH_PAT }} # `GH_PAT` is a secret that contains your PAT

    #- name: Set up QEMU
    #  uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v5
      with:
        # list of Docker images to use as base name for tags
        images: |
          quay.io/kenmoini/symphony
        # generate Docker tags based on the following events/attributes
        tags: |
          type=schedule
          type=ref,event=branch
          type=ref,event=tag
          type=sha,prefix=,suffix=,format=short
          type=sha,prefix=,suffix=,format=long
          type=raw,value=latest

    #- name: Login to RH Container Registry
    #  uses: docker/login-action@v3
    #  with:
    #    registry: registry.redhat.io
    #    username: "${{ secrets.RH_REGISTRY_USER }}"
    #    password: "${{ secrets.RH_REGISTRY_TOKEN }}"

    - name: Login to Quay Container Registry
      uses: docker/login-action@v3
      with:
        registry: quay.io
        username: "${{ secrets.REGISTRY_USERNAME }}"
        password: "${{ secrets.REGISTRY_TOKEN }}"

    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: ./apps/symphony/
        file: ./apps/symphony/Containerfile
        labels: ${{ steps.meta.outputs.labels }}
        tags: ${{ steps.meta.outputs.tags }}
        push: true
        cache-from: type=gha
        cache-to: type=gha,mode=max
        #platforms: linux/amd64, linux/arm64

    - name: Template the Deployment to redeploy via ArgoCD
      run: |
        sed -i "s|quay.io/kenmoini/symphony:latest|quay.io/kenmoini/symphony:${{ github.sha }}|g" ./microshift/symphony/deployment.yml

    #- name: Commit changes
    #  run: |
    #    date > generated.txt
    #    git config user.name github-actions
    #    git config user.email github-actions@github.com
    #    git add .
    #    git commit -m "generated"
    #    git push
        
    - name: Commit changes
      uses: EndBug/add-and-commit@v9
      with:
        #author_name: GitHub Actions
        #author_email: gha@kemo.network
        message: 'Update Symphony container image to latest commit'
        pull: '--ff-only'
        add: 'microshift/symphony/deployment.yml'
