---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Deploys the banana-phone microservice
# namespace: banana-phone

resources:
  - namespace.yml
  - deployment.yml
  - service.yml
  - route.yml
