# Or generate the secret with

# kubectl create secret generic twilio-credentials -n banana-phone --from-literal=twlioAccountSID=YOUR_SID --from-literal=twilioAuthToken=YOUR_TOKEN --from-literal=twilioFromNumber="+15558675309"
---
apiVersion: v1
kind: Secret
metadata:
  name: twilio-credentials
  namespace: banana-phone
stringData:
  twlioAccountSID: twlioAccountSIDHere
  twilioAuthToken: twilioAuthTokenHere
  twilioFromNumber: "+15558675309"
